// Originally generated by Lovable; now maintained by hand so credentials come from env, not source.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configured via .env (see .env.example) — never hardcode project credentials here
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Copy .env.example to .env and fill them in."
  );
}

const isDev = typeof import.meta !== "undefined" ? import.meta.env.DEV : false;

const loggingFetch: typeof fetch = async (input, init) => {
  if (isDev) {
    const method = init?.method ?? (input instanceof Request ? input.method : "GET");
    const url = input instanceof Request ? input.url : String(input);
    console.log("[Supabase request]", method, url);
  }

  try {
    const response = await fetch(input as RequestInfo, init);
    if (isDev) {
      console.log("[Supabase response]", response.status, response.url);
    }
    return response;
  } catch (error) {
    if (isDev) {
      console.error("[Supabase fetch error]", error);
    }
    throw error;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    fetch: loggingFetch,
  }
});